//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.alivc.videochat.publisher;

public interface MediaError {
  int ALIVC_SUCCESS_PUBLISH = 0;
  int ALIVC_INFO_LAUNCH_CHAT_END = -2001;
  int ALIVC_INFO_ABORT_CHAT_END = -2002;
  int ALIVC_INFO_ONLINE_CHAT_END = -2003;
  int ALIVC_INFO_OFFLINE_CHAT_END = -2004;
  int ALIVC_INFO_ADD_CHAT_END = -2005;
  int ALIVC_INFO_REMOVE_CHAT_END = -2006;
  int ALIVC_ERR_MEMORY_POOR = -100;
  int ALIVC_ERR_PUBLISHER_OPEN_FAILED = -101;
  int ALIVC_ERR_PUBLISHER_ILLEGAL_ARGUMENT = -200;
  int ALIVC_ERR_PUBLISHER_NETWORK_UNCONNECTED = -400;
  int ALIVC_ERR_PUBLISHER_AUDIO_CAPTURE_DISABLED = -401;
  int ALIVC_ERR_PUBLISHER_VIDEO_CAPTURE_DISABLED = -402;
  int ALIVC_ERR_PUBLISHER_MALLOC_FAILED = -403;
  int ALIVC_ERR_PUBLISHER_VIDEO_ENCODER_INIT_FAILED = -404;
  int ALIVC_ERR_PUBLISHER_AUDIO_ENCODER_INIT_FAILED = -405;
  int ALIVC_ERR_PUBLISHER_SEND_DATA_TIMEOUT = -406;
  int ALIVC_ERR_PUBLISHER_NETWORK_POOR = -407;
  int ALIVC_ERR_PUBLISHER_ENCODE_AUDIO_FAILED = -408;
  int ALIVC_ERR_PUBLISHER_ENCODE_VIDEO_FAILED = -409;
  int ALIVC_ERR_PUBLISHER_VIDEO_CAPTURE_FPS_SLOW = -410;
  int ALIVC_ERR_PUBLISHER_AUDIO_CAPTURE_NO_DATA = -411;
  int ALIVC_ERR_PUBLISHER_VIDEO_CAPTURE_NO_DATA = -412;
  int ALIVC_INFO_PUBLISH_NETWORK_GOOD = -500;
  int ALIVC_INFO_PUBLISH_RECONNECT_START = -501;
  int ALIVC_INFO_PUBLISH_RECONNECT_SUCCESS = -502;
  int ALIVC_INFO_PUBLISH_RECONNECT_FAILURE = -503;
  int ALIVC_INFO_PUBLISH_DISPLAY_FIRST_FRAME = -504;
  int ALIVC_INFO_PUBLISH_START_SUCCESS = -505;
  int ALIVC_SUCCESS = 0;
  int ALIVC_ERR_PLAYER_UNKNOW = -1001;
  int ALIVC_ERR_PLAYER_UNSUPPORTED = -1002;
  int ALIVC_ERR_PLAYER_TIMEOUT = -1003;
  int ALIVC_ERR_PLAYER_OPEN_FAILED = 400;
  int ALIVC_ERR_PLAYER_NO_NETWORK = 401;
  int ALIVC_ERR_PLAYER_READ_PACKET_TIMEOUT = 511;
  int ALIVC_ERR_PLAYER_NO_SURFACEVIEW = 503;
  int ALIVC_ERR_PLAYER_INVALID_INPUTFILE = 504;
  int ALIVC_ERR_PLAYER_INVALID_CODEC = 505;
  int ALIVC_ERR_PLAYER_NO_MEMORY = 506;
  int ALIVC_ERR_PLAYER_AUDIO_PLAY = 512;
  int ALIVC_INFO_PLAYER_FIRST_FRAME_RENDERED = 3;
  int ALIVC_INFO_PLAYER_BUFFERING_START = 101;
  int ALIVC_INFO_PLAYER_BUFFERING_END = 102;
  int ALIVC_INFO_PLAYER_NETWORK_POOR = 104;
  int ALIVC_INFO_PLAYER_PREPARED_PROCESS_FINISHED = 150;
  int ALIVC_INFO_PLAYER_INTERRUPT_PLAYING = 151;
  int ALIVC_INFO_PLAYER_STOP_PROCESS_FINISHED = 152;
}
